---
# Some input validation on the region
- set_fact: region="{{ lookup('env','CLOUDSTACK_REGION') }}"
- set_fact: valid_regions="['LAB','DEV','PHX','ASH']"
- assert:
    that: region in valid_regions
    msg: "This is an invalid region. Valid regions: LAB, DEV, PHX, ASH"

# Some global facts
- name: Setting facts for the region
  set_fact:
    enabled_tag: "enabled=true"

# Include POD and Clusters var file based on regions name
- name: include pods variables
  include_vars: roles/cloudstack-pods/vars/{{ region }}-pods.yml

- name: include clusters variables
  include_vars: roles/cloudstack-pods/vars/{{ region }}-clusters.yml

- debug: msg="Creating PODs in {{ region }}"
- include_tasks: roles/cloudstack-pods/tasks/pods.yml

- debug: msg="Creating clusters in {{ region }}"
- include_tasks: roles/cloudstack-pods/tasks/clusters.yml

- debug: msg="Adding hosts in {{ region }}"
- include_tasks: roles/cloudstack-pods/tasks/hosts.yml
  with_dict: "{{ clusters }}"
  loop_control:
    loop_var: outer_item

- debug: msg="Adding storage to clusters in {{ region }}"
- include_tasks: roles/cloudstack-pods/tasks/storage.yml
  with_dict: "{{ clusters }}"
  loop_control:
    loop_var: outer_item
