---
  # These tasks should only be done during KickStart - they are NOT inteded to be safe on
  # a hypervisor that has been fully installed/configured
  # - name: "Create custom facts directory"
  #   file:
  #     path: "/etc/ansible/facts.d"
  #     state: "directory"
    
  ## Re-running setup is REQUIRED at this point since we have to consider
  ## the fact that we may be running AFTER the kickstart role which sets 
  ## The system's hostname and other facts
  - name: "Re-run setup to use custom facts"
    setup: ~
  
  - name: Get Installed YUM Package list 
    yum:
      list=installed
    register: installed_yum_packages
    tags: yum_pkgs

  # Figure out what site/dc we are operating in
  - import_tasks: roles/common/tasks/site.yml
    tags: site

  # Configure Cloudstack Repo
  - import_tasks: roles/common/tasks/cloudstack_repo.yml

  # Install Common Packages
  - import_tasks: roles/common/tasks/packages.yml
    
  # Setup Resolver
  - import_tasks: roles/common/tasks/resolver.yml
  
  # Setup NTP/Chrony
  - import_tasks: roles/common/tasks/chrony.yml
  
  # Install node-exporter packages
  - import_tasks: roles/common/tasks/node-exporter.yml
  
  # Install and setup teleport 
  - import_tasks: roles/common/tasks/teleport.yml
    tags: teleport
  
  # Install and setup OSSEC 
  - import_tasks: roles/common/tasks/ossec.yml
    tags: ossec
  
  # Setup rsyslog central server 
  - import_tasks: roles/common/tasks/rsyslog.yml
    tags: rsyslog
  
  # Disable CentOS upgrade from public repos  
  # - import_tasks: roles/common/tasks/repos.yml
  
