# - name: Check if OSSEC is already installed
#   command: rpm -q ossec-hids-server
#   register: ossec_install_status

- debug: var=item
  with_items: "{{installed_yum_packages|json_query(jsonquery)}}"
  vars:
    jsonquery: "results[?name=='ossec-hids-server']"
  register: ossec_install_status

- name: Check for the /var/ossec/etc/ossec.conf file exists
  stat:
    path: /var/ossec/etc/ossec.conf
  register: ossec_conf_present

- name: Install the OSSEC RPMs
  yum:  name={{ item }} state=present update_cache=yes
  with_items:
    - http://maven.platform.tm.tmcs:8081/nexus/content/repositories/releases/com/ticketmaster/techops-infra/cloudstack/inotify-tools-3.13-2.el7.art.x86_64.rpm
    - http://maven.platform.tm.tmcs:8081/nexus/content/repositories/releases/com/ticketmaster/techops-infra/cloudstack/ossec-hids-2.9.3-2833.el7.art.x86_64.rpm
    - http://maven.platform.tm.tmcs:8081/nexus/content/repositories/releases/com/ticketmaster/techops-infra/cloudstack/ossec-hids-server-2.9.3-2833.el7.art.x86_64.rpm
  when: ossec_install_status.version is not defined

- name: Copy OSSEC configuration file
  copy:
    src: roles/common/files/ossec.conf
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: 0644
  when: ossec_install_status.version is not defined or ossec_conf_present.stat.isreg is not defined

- name: Enable OSSEC 
  ignore_errors: yes
  systemd:
    name: ossec-hids  
    enabled: yes
    state: started
  when: ossec_install_status.version is not defined or ossec_conf_present.stat.isreg is not defined
