## TODO: There should be a better way of detecting if teleport is configured and working
##       Do it better later
## for right now when teleport_install_status.rc == 3, this means the service is 'unknown'
- name: Check if Teleport is installed
  ignore_errors: true
  command: systemctl is-active --quiet teleport.service
  register: teleport_install_status
  changed_when: False
##  ^^ Only works after Kickstart is done and OS is running - during the kickstart it doesnt return a RC of 3 :/
## SystemD isnt fully functional during Kickstart

- name: Check if Teleport service manifest exists
  stat:
    path: /etc/systemd/system/teleport.service
  register: teleport_service_present

- name: Check for the /etc/teleport.yaml file exists
  stat:
    path: /etc/teleport.yaml
  register: teleport_yaml_present

- name: Download teleport binary
  unarchive:
    src: http://maven.platform.tm.tmcs:8081/nexus/content/repositories/releases/com/ticketmaster/techops-infra/teleport/teleport-ent-v2.4.0-linux-amd64-bin.tar.gz
    dest: /opt/
    remote_src: True
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3) or teleport_service_present.stat.isreg is not defined

- name: Install teleport
  shell: /opt/teleport-ent/install
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3) or teleport_service_present.stat.isreg is not defined

- name: Install systemd Config File
  copy:
    src: roles/common/files/teleport.service
    dest: /etc/systemd/system/teleport.service
    owner: root
    group: root
    mode: 0644
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3) or teleport_service_present.stat.isreg is not defined

- name: Site Detected {{ tm_site }}
  debug: var=tm_site

- name: Install Teleport Config File for PHX
  template:
    src: teleport-phx.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: 0644
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3 and tm_site == "PHX" ) or ( teleport_service_present.stat.isreg is not defined and tm_site == "PHX" ) or ( teleport_yaml_present.stat.isreg is not defined and tm_site == "PHX" )


- name: Install Teleport Config File for ASH 
  template:
    src: teleport-ash.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: 0644
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3 and tm_site == "ASH" ) or ( teleport_service_present.stat.isreg is not defined and tm_site == "ASH" ) or ( teleport_yaml_present.stat.isreg is not defined and tm_site == "ASH" )

- name: Install Teleport Config File for LON 
  template:
    src: teleport-lon.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: 0644
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3 and tm_site == "LON1" ) or ( teleport_service_present.stat.isreg is not defined and tm_site == "LON1" ) or ( teleport_yaml_present.stat.isreg is not defined and tm_site == "LON1" )

- name: Install Teleport Config File for AMS 
  template:
    src: teleport-lon.yaml.j2
    dest: /etc/teleport.yaml
    owner: root
    group: root
    mode: 0644
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3 and tm_site == "AMS1" ) or ( teleport_service_present.stat.isreg is not defined and tm_site == "AMS1" ) or ( teleport_yaml_present.stat.isreg is not defined and tm_site == "AMS1" )

- name: Update systemd for Teleport
  ignore_errors: yes
  systemd:
    name: teleport.service
    enabled: yes
    state: started
    daemon_reload: yes
  when: (teleport_install_status.rc is defined and teleport_install_status.rc == 3) or ( teleport_service_present.stat.isreg is not defined ) or ( teleport_yaml_present.stat.isreg is not defined )
