---
# Some input validation on the region
- set_fact: region="{{ lookup('env','CLOUDSTACK_REGION') }}"

- set_fact: valid_regions="['LAB','DEV','PHX','ASH']"

- assert:
    that: region in valid_regions
    msg: "This is an invalid region. Valid regions: LAB, DEV, PHX, ASH"

# Some global facts
- name: Setting facts for the region
  set_fact:
    netoffer_name: "ExternalTenantNetwork"
    enabled_tag: "enabled=true"

# Set vars that are region specific
- name: setting fact for LAB region
  set_fact:
    zones: "['LAB1','LAB2']"
    ldap_server: "ldaps.pci-tmaws.io"
  when: region == "LAB"

- name: setting fact for DEV region
  set_fact:
    zones: "['DEV1']"
    ldap_server: "ldaps.pci-tmaws.io"
  when: region == "DEV"

- name: setting fact for ASH region
  set_fact:
    zones: "['ASH1','ASH2','CAP2']"
    ldap_server: "ldaps-ash2.techops.info"
  when: region == "ASH"

- name: setting fact for PHX region
  set_fact:
    zones: "['PHX1','PHX2']"
    ldap_server: "ldaps-phx2.techops.info"
  when: region == "PHX"

# Set subdomain
# All in root for now
#- import_tasks: roles/cloudstack-controller-zones/tasks/domains.yml

# Set Global settings
- import_tasks: roles/cloudstack-controller-zones/tasks/global_settings.yml
  tags: zones_only

# Add ldap configurations
#- import_tasks: roles/cloudstack-controller-zones/tasks/ldap.yml
#  tags: zones_only


# Create zones
- debug: msg="Creating {{ zones }} zones"
- include_tasks: roles/cloudstack-controller-zones/tasks/zones.yml
  with_items: "{{ zones }}"
  loop_control:
    loop_var: outer_item
  tags: zones_only

# Create Networks and compute offerings
- name: include GP1 service offer variables
  include_vars: roles/cloudstack-controller-zones/vars/gp1_service_offers.yml

- name: include GP2 service offer variables
  include_vars: roles/cloudstack-controller-zones/vars/gp2_service_offers.yml

- debug: msg="Creating networks and compute offers in {{ region }}"
- include_tasks: roles/cloudstack-controller-zones/tasks/offerings.yml


# Create projects and networks
- name: include nonprod networks variables
  include_vars: roles/cloudstack-controller-zones/vars/lab_networks.yml
  when: region == "LAB"

- name: include nonprod networks variables
  include_vars: roles/cloudstack-controller-zones/vars/nonprod_networks.yml
  when: region == "DEV"

- name: include prod networks variables
  include_vars: roles/cloudstack-controller-zones/vars/ash_prod_networks.yml
  when: region == "ASH"

- name: include prod networks variables
  include_vars: roles/cloudstack-controller-zones/vars/phx_prod_networks.yml
  when: region == "PHX"

- debug: msg="Creating networks in {{ region }}"
- include_tasks: roles/cloudstack-controller-zones/tasks/networks.yml
