# Create tenant projects from dict
- local_action:
    module: cs_project
    name: tenant-{{ item.value.vlan }}
  with_dict: "{{ networks }}"

# Create networks from dict
- local_action:
    module: cs_network
    name: "{{ item.value.name }}"
    zone: "{{ item.value.zone }}"
    domain: "{{ item.value.domain }}"
    project: tenant-{{ item.value.vlan }}
    acl_type: account
    network_offering: "{{ netoffer_name}}"
    vlan: "{{ item.value.vlan }}"
    start_ip: "{{item.value.startip}}"
    end_ip: "{{item.value.endip}}"
    netmask: "{{item.value.netmask}}"
    gateway: "{{item.value.gateway}}"
  with_dict: "{{ networks }}"
