# Create the shared network offer with no service
# This prevents the deployment of virtual router in order
# to use an external DHCP service

- name: Create external network offering
  shell: >
    cs createNetworkOffering displaytext="{{ netoffer_name }}" supportedservices=""
    guestiptype=Shared name="{{ netoffer_name }}" traffictype=GUEST
    SpecifyVlan=true SpecifyIpRanges=true networkrate=-1

- name: Lookup offer ID
  shell: cs listNetworkOfferings name="{{ netoffer_name }}"
  register: netoffer

- name: Parse results of netoffer
  set_fact:
    offer: "{{ netoffer.stdout | from_json }}"

- name: Set ID from new-net
  set_fact:
    offerid: "{{ offer.networkoffering.0.id }}"

- name: Enable external network offering
  shell: cs updateNetworkOffering id="{{ offerid }}" state=Enabled


# Create the various compute offerings.
- name: Create GP1 compute offerings
  shell: >
    if $(cs -q listServiceOfferings name="{{ item.key }}" | jq -e ".count | length == 0"); then
    cs createServiceOffering displaytext="{{ item.value.desc }}" name="{{ item.key }}"
    cpunumber="{{ item.value.vcpus }}" cpuspeed=2000 deploymentplanner=UserDispersingPlanner
    hosttags="cpuclass=GP1" offerha=true storagetype=shared provisioningtype=thin
    memory="{{ item.value.mem }}"; fi
  with_dict: "{{ gp1_compute_offers }}"

- name: Create GP2 compute offerings
  shell: >
    if $(cs -q listServiceOfferings name="{{ item.key }}" | jq -e ".count | length == 0"); then
    cs createServiceOffering displaytext="{{ item.value.desc }}" name="{{ item.key }}"
    cpunumber="{{ item.value.vcpus }}" cpuspeed=2000 deploymentplanner=UserDispersingPlanner
    hosttags="cpuclass=GP2" offerha=true storagetype=shared provisioningtype=thin
    memory="{{ item.value.mem }}"; fi
  with_dict: "{{ gp2_compute_offers }}"
