---
# These tasks should only be done during KickStart - they are NOT inteded to be safe on
# a hypervisor that has been fully installed/configured
- name: "Create custom facts directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"
  
- name: "Re-run setup to use custom facts"
  setup: ~

# Install Hypervisor Packages
- import_tasks: roles/cloudstack-hypervisor/tasks/packages.yml

# Enable OpenVSwitch
- import_tasks: roles/cloudstack-hypervisor/tasks/openvswitch.yml

# Cleanup libvirt default networking
- import_tasks: roles/cloudstack-hypervisor/tasks/libvirt_virtualnets.yml

# Add Users and Sudo info
- import_tasks: roles/cloudstack-hypervisor/tasks/users_and_perms.yml

# Configure libvirt
- import_tasks: roles/cloudstack-hypervisor/tasks/libvirtd_config.yml

# Configure Cloudstack Agent INI
- import_tasks: roles/cloudstack-hypervisor/tasks/cloudstack_agent_configuration.yml

# Configure Cloudstack Autofencing of hypervisors
- import_tasks: roles/cloudstack-hypervisor/tasks/cloudstack_autofencing.yml

# Configure tuned-adm
- import_tasks: roles/cloudstack-hypervisor/tasks/tunedadm.yml