- name: Install Essential Packages for a KVM Hypervisor
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - qemu-kvm-tools
    - qemu-kvm-common
    - qemu-kvm
    - libguestfs-tools-c
    - virt-top
    - virt-manager
    - python-lxml
    - cloudstack-agent
    - libguestfs-tools 
    - virt-top