---
- hosts: all
  vars_prompt:
  - name: new_root_pwd
    prompt: "New Root Password"
    private: yes
    #    encrypt: "sha512_crypt"
    confirm: yes
    #    salt_size: 7
  tasks:
  - name: Change Password
    user:
      name: root
      password: "{{ new_root_pwd | password_hash('sha512') }}"
      update_password: always
